export { default as Header } from './Header'
export { default as AboutUs } from './AboutUs'
export { default as Footer } from './Footer'
export { default as AuthorPage } from './AuthorPage'
export { default as Subscribe } from './Subscribe'
export { default as MainSlider } from './Slider'
